id = "properties"
name = "Java Properties"
version = "0.0.1"
schema_version = 1
authors = ["ruud651"]
description = "Java Properties extension"
repository = "https://github.com/Ruud651/properties-zed"

[grammars.properties]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-properties"
commit = "f93f673990deffbfa548826eebade93af81887b4"
