id = "java-properties"
name = "Java Properties"
version = "0.0.1"
schema_version = 1
authors = ["Your Name <you@example.com>"]
description = "My cool extension"
repository = "https://github.com/your-name/my-zed-extension"

[grammars.java-properties]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-properties"
commit = "f93f673990deffbfa548826eebade93af81887b4"
